image: node:22.12.0

cache:
  paths:
     - node_modules/

build:
  script:
    - npm i
    - export NODE_ENV=production
    - npm run build
  artifacts:
    paths:
      - dist
  only: 
    - main

deploy:
  script:
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    paths:
      - public
  only:
    - main